//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DavidKinectTFG2016.idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idiomas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DavidKinectTFG2016.idiomas.idiomas", typeof(idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adquerir....
        /// </summary>
        public static string buttonAdquerirPacientes {
            get {
                return ResourceManager.GetString("buttonAdquerirPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string buttonCancelar {
            get {
                return ResourceManager.GetString("buttonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar....
        /// </summary>
        public static string buttonConsultar {
            get {
                return ResourceManager.GetString("buttonConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar....
        /// </summary>
        public static string buttonConsultarPacientes {
            get {
                return ResourceManager.GetString("buttonConsultarPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio....
        /// </summary>
        public static string buttonEjercicio {
            get {
                return ResourceManager.GetString("buttonEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        public static string buttonIniciar {
            get {
                return ResourceManager.GetString("buttonIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string buttonModificar {
            get {
                return ResourceManager.GetString("buttonModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse....
        /// </summary>
        public static string buttonRegistrar {
            get {
                return ResourceManager.GetString("buttonRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adquerir pacientes: .
        /// </summary>
        public static string labelAdquerirPacientes {
            get {
                return ResourceManager.GetString("labelAdquerirPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos:.
        /// </summary>
        public static string labelApellidos {
            get {
                return ResourceManager.GetString("labelApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar mis ejercicios:.
        /// </summary>
        public static string labelConsultar {
            get {
                return ResourceManager.GetString("labelConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar mis pacientes:.
        /// </summary>
        public static string labelConsultarPacientes {
            get {
                return ResourceManager.GetString("labelConsultarPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string labelContraseña {
            get {
                return ResourceManager.GetString("labelContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer ejercicio:.
        /// </summary>
        public static string labelEjercicio {
            get {
                return ResourceManager.GetString("labelEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija un paciente libre:.
        /// </summary>
        public static string labelEnunciadoElegirPaciente {
            get {
                return ResourceManager.GetString("labelEnunciadoElegirPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado:.
        /// </summary>
        public static string labelEstado {
            get {
                return ResourceManager.GetString("labelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Paciente: .
        /// </summary>
        public static string labelIDPaciente {
            get {
                return ResourceManager.GetString("labelIDPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Pacientes:.
        /// </summary>
        public static string labelModificarPacientes {
            get {
                return ResourceManager.GetString("labelModificarPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Terapeutas:.
        /// </summary>
        public static string labelModificarTerapeutas {
            get {
                return ResourceManager.GetString("labelModificarTerapeutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacimiento:.
        /// </summary>
        public static string labelNacimiento {
            get {
                return ResourceManager.GetString("labelNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NIF:.
        /// </summary>
        public static string labelNIF {
            get {
                return ResourceManager.GetString("labelNIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre paciente elegido:.
        /// </summary>
        public static string labelNombreElegirPaciente {
            get {
                return ResourceManager.GetString("labelNombreElegirPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir contraseña:.
        /// </summary>
        public static string labelRepetirContraseña {
            get {
                return ResourceManager.GetString("labelRepetirContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar el ejercicio:.
        /// </summary>
        public static string labelSeleccionEjercicio {
            get {
                return ResourceManager.GetString("labelSeleccionEjercicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono:.
        /// </summary>
        public static string labelTelefono {
            get {
                return ResourceManager.GetString("labelTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo usuario:.
        /// </summary>
        public static string labelTipoUsuario {
            get {
                return ResourceManager.GetString("labelTipoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BIENVENIDO A KINECT:.
        /// </summary>
        public static string labelTitulo {
            get {
                return ResourceManager.GetString("labelTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione la opción que desee:.
        /// </summary>
        public static string labelTituloAdministrador {
            get {
                return ResourceManager.GetString("labelTituloAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pacientes que se encuentran sin terapeuta:.
        /// </summary>
        public static string labelTituloAdquerirPacientes {
            get {
                return ResourceManager.GetString("labelTituloAdquerirPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estos son tus pacientes:.
        /// </summary>
        public static string labelTituloConsultarPacientes {
            get {
                return ResourceManager.GetString("labelTituloConsultarPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este es tu historial de ejercicios: .
        /// </summary>
        public static string labelTituloHistorialPaciente {
            get {
                return ResourceManager.GetString("labelTituloHistorialPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, seleccione la opción que desee:.
        /// </summary>
        public static string labelTituloPaciente {
            get {
                return ResourceManager.GetString("labelTituloPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, seleccione la opción que desee:.
        /// </summary>
        public static string labelTituloTerapeuta {
            get {
                return ResourceManager.GetString("labelTituloTerapeuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string labelUsuario {
            get {
                return ResourceManager.GetString("labelUsuario", resourceCulture);
            }
        }
    }
}
