//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DavidKinectTFG2016
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Pacientes
    {
        public int idPaciente { get; set; }
        public string nombrePaciente { get; set; }
        public string apellidosPaciente { get; set; }
        public string usuario { get; set; }
        public string nifPaciente { get; set; }
        public string telefonoPaciente { get; set; }
        public System.DateTime nacimientoPaciente { get; set; }
        public string estadoPaciente { get; set; }

        public static explicit operator Pacientes(DbSet<Pacientes> v)
        {
            throw new NotImplementedException();
        }

        public virtual Usuarios Usuarios { get; set; }
    }
}
