//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DavidKinectTFG2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relaciones
    {
        public int idRelacion { get; set; }
        public int idPaciente { get; set; }
        public int idTerapeuta { get; set; }
        public string nombrePaciente { get; set; }
        public string apellidosPaciente { get; set; }
        public string nombreTerapeuta { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public string fechaFin { get; set; }
    }
}
